language: node_js
# node_js: "12"

os:
- linux
# - osx

dist: xenial
# osx_image: xcode10.1

cache:
  npm: true
  directories:
  - $HOME/.cache/electron

    # addons:
    # apt:
    # packages:
    # - fakeroot
    # - rpm

install:
- yarn install

script:
- yarn run lint
- yarn test
- if test -z "$TRAVIS_TAG"; then yarn run make; fi

after_success: if test -n "$TRAVIS_TAG"; then yarn run publish; fi

branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+/
