name: Electron Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    name: Node JS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Print ref
        run: echo ${{ github.ref }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint JS
        run: yarn run lint
      - name: Test JS
        run: yarn test
      - name: Build Electron
        run: yarn run make
